### ISSUE TITLE
JWT Keys

### ISSUE THREAD

**Issue by fartabomination** [xinweny/discord-clone#1]
Just wondering what I need to do here:

```bat
# Authentication
JWT_ACCESS_SECRET=
JWT_REFRESH_SECRET=
JWT_RESET_SECRET=

JWT_ACCESS_EXPIRE= # e.g. 300s, 15m, 1h 
JWT_REFRESH_EXPIRE=# e.g. 60d
```

**Comment by fartabomination** [comment]
Sorry, I just entered a random generated code into them (for the keys)

**Comment by drmaynard1** [comment]
> Sorry, I just entered a random generated code into them (for the keys)

i was having the same issue glad i saw this!
