### ISSUE TITLE
Cloudinary not uploading images

### ISSUE THREAD

**Issue by fartabomination** [xinweny/discord-clone#3]
Whenever I upload an image to the discord clone and have setup cloudinary correctly I get this
![image](https://github.com/xinweny/discord-clone/assets/115855298/08725043-693e-4cd1-9971-31795499049c)

And if I click it I get this
![image](https://github.com/xinweny/discord-clone/assets/115855298/0ab8a85f-422f-400d-86bc-5e3cba3c63fb)

If I look on the Cloudinary dashboard I can acctualy see that it records the 404 errors meaning that it is set up correctly in the .env.
![image](https://github.com/xinweny/discord-clone/assets/115855298/669bfae4-13d0-447c-85d5-39c3067635b0)

Can you please fix this?

(Also same happens when uploading custom profile pictures).

**Comment by xinweny** [comment]
Hi, this error was due to a typo in retrieving one of the cloudinary env variables on the client side - it is now fixed.
