### ISSUE TITLE
status icons/dm icons/friend icons

### ISSUE THREAD

**Issue by drmaynard1** [xinweny/discord-clone#4]
hi i was just wondering if it is possible to get icons when you get dm'ed so it has the number of times you where dmed by that user and if their pfp shows in the side bar (with the numbers like discord does) and if there can be something like this when you get friended so the count shows on the discord logo and on the friends tab. i was also wondering if it is possible to have status icons inside the server list like discord does?

**Comment by drmaynard1** [comment]
or even a dnd mode. i think it would also be preferable if the status icons also showed in the server members list

**Comment by xinweny** [comment]
Thanks for your suggestions, but this is a personal project for learning purposes - I'm not looking to add any new features at the moment.

**Comment by drmaynard1** [comment]
sure, no problem!
